name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: One line script
      run: echo hello, Alex
    - name: Two line script
      run: |
        echo you are,
        echo GREAT
